import Head from "next/head";
import { type NextPage } from "next";
import Calendar from "react-calendar";
import "react-calendar/dist/Calendar.css";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const [firstDate, setFirstDate] = useState(new Date(2021, 4, 1));
  const router = useRouter();

  const onChange = () => {
    setFirstDate(firstDate);
  };

  const chosenDate = (date: Date) => {
    const month = (date.getMonth() + 1).toString().padStart(2, "0");
    const day = date.getDate().toString().padStart(2, "0");
    const formattedDate = `${date.getFullYear()}-${month}-${day}`;
    return formattedDate;
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        {/* <Map /> */}
        <h1 className="text-4xl font-bold">
          Welcome to Helsinki city bike app!
        </h1>
        <text className="text-center text-2xl ">Choose a date</text>
        <Calendar
          value={firstDate}
          onChange={onChange}
          minDate={new Date(2021, 4, 1)}
          maxDate={new Date(2021, 6, 30)}
          // On click day, navigate to rides-by-day page
          onClickDay={(value: Date) => {
            const format_date = chosenDate(value);
            console.log(format_date);
            router.push({
              pathname: "/rides-by-day",
              query: { date: format_date },
            });
          }}
        />
      </main>
    </>
  );
};

export default Home;
