import Head from "next/head";
import { type NextPage } from "next";
import Calendar from "react-calendar";
import {useCookies} from 'react-cookie';
import "react-calendar/dist/Calendar.css";
import { useState} from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const [firstDate, setFirstDate] = useState(new Date(2021, 4, 1));
  const [pageCookie, setPageCookie] = useCookies(['page']);
  const router = useRouter();

  const onChange = () => {
    setFirstDate(firstDate);
  };

  const chosenDate = (date: Date) => {
    const month = (date.getMonth() + 1).toString().padStart(2, "0");
    const day = date.getDate().toString().padStart(2, "0");
    return `${date.getFullYear()}-${month}-${day}`;
  };

    setPageCookie('page', 1, {path: '/rides-by-day', expires: new Date(Date.now() + 86400 * 1000)});
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center space-y-5 ">
        <h1 className="text-4xl font-bold">
          Welcome to Helsinki city bike app!
        </h1>
        <text className="text-center text-2xl ">Choose a date</text>
        <Calendar
          value={firstDate}
          onChange={onChange}
          minDate={new Date(2021, 4, 1)}
          maxDate={new Date(2021, 6, 30)}
          onClickDay={(value: Date) => {
            const format_date = chosenDate(value);
              router.push({
              pathname: "/rides-by-day",
              query: { date: format_date, page: 1 },
            });
          }}
        />
      </main>
    </>
  );
};

export default Home;
